controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

login:
    path: /
    controller: App\Controller\ConnexionController::index

accueil:
    path: /accueil
    controller: App\Controller\AccueilController::index